### ISSUE TITLE
Motivation & Comparisons?

### ISSUE THREAD

**Issue by lowercase00** [long2ice/rearq#10]
Hi there.
I wonder if you could share a bit about the project's motivations, I'm curious on why this was not a PR to Arq, what are the main pain points that made you write this instead of using Celery/RQ/Dramatiq/Arq. 
Thanks!

**Comment by long2ice** [comment]
Hello, before I want find something like `celery` in asyncio, I found `arq` and try it. But I don't like its api and I want make improvement according to my mind, which is big and I'm afraid `arq` can't accept it, so I make this project.

**Comment by ramnes** [comment]
Hey there! Great work with the API and dashboard @long2ice, but why not build on top of Arq rather than rewriting it? Arq has quite some traction at the moment, and as a user I'd feel safer if ReArq was based on a core library that's widely used and reviewed.
