### ISSUE TITLE
How to add corn tasks dynamically?

### ISSUE THREAD

**Issue by qianmianyao** [long2ice/rearq#15]
Is it currently only possible to write timed tasks to death in the program?
```python
@rearq.task(cron="0 * * * *")
async def timer_add():
    return "timer"
```

**Comment by long2ice** [comment]
Just use `rearq.create_task`

**Comment by qianmianyao** [comment]
> 只需使用`rearq.create_task`

Hi, I checked the create_task method and it has an extra callback function, but I still don't know how to use it, for example, I want to create dynamically timed tasks for different time periods through front-end api calls, is this possible?

I mean is the place cron="0 * * * * *" written dead.

**Comment by long2ice** [comment]
That's not supported now
