### ISSUE TITLE
job.result() return ValidationError

### ISSUE THREAD

**Issue by cnc8** [long2ice/rearq#3]
Hello. Thanks for rearq

When I try to get the result of the task I get the error:
```
...
File "/mnt/c/fastatz/venv/lib/python3.8/site-packages/rearq/job.py", line 103, in result_info
    return JobResult.parse_obj(v)
  File "pydantic/main.py", line 454, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for JobResult
__root__
  JobResult expected dict not bytes (type=type_error)
```

Redis returns a byte object and pydantic cannot read it.

I replaced from `return JobResult.parse_obj(v)` to `return JobResult.parse_raw(v)`. 
Another option is to use json.loads()
Please fix that :)

**Comment by long2ice** [comment]
Fixed that, thanks!
