### ISSUE TITLE
job_retry

### ISSUE THREAD

**Issue by PY-GZKY** [long2ice/rearq#9]
你好作者，我发现任务的 job_retry 参数依然存在，但是并没有看到重试的方法。

它进入了 redis 的延迟队列中，但好像得不到调度。

**Comment by long2ice** [comment]
现在的逻辑是失败后会再次进入队列
https://github.com/long2ice/rearq/blob/dev/rearq/worker.py#L203

**Comment by PY-GZKY** [comment]
好的，感谢。
